### ISSUE TITLE
Sample larger than population or is negative

### ISSUE THREAD

**Issue by Ilyaprok** [edenartlab/sd-lora-trainer#10]
Traceback (most recent call last):                           └───────────────────────────┘
  File "C:\Users\ilya9\comf_lora\ComfyUI\custom_nodes\sd-lora-trainer\main.py", line 565, in <module>
    for progress in train(config=config):
  File "C:\Users\ilya9\comf_lora\ComfyUI\custom_nodes\sd-lora-trainer\main.py", line 433, in train
    validation_prompts = render_images(
  File "C:\Users\ilya9\anaconda3\envs\comf_lora\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ilya9\comf_lora\ComfyUI\custom_nodes\sd-lora-trainer\trainer\inference.py", line 326, in render_images
    validation_prompts_raw = random.sample(val_prompts["object"], n_imgs)
  File "C:\Users\ilya9\anaconda3\envs\comf_lora\lib\random.py", line 482, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

**Comment by Ilyaprok** [comment]
my config:
{
    "name": "fudzi2",
    "sd_model_version": "sdxl",
	"ckpt_path": "C:\\Users\\ilya9\\comf_lora\\ComfyUI\\models\\checkpoints\\sd_xl_base_1.0_0.9vae.safetensors",
    "lora_training_urls": "D:/Downloads/tmp/iselgan_neuro/iselgan_src/fudzi/fudzi",
    "concept_mode": "object",
    "sample_imgs_lora_scale": 0.75,
    "seed": 0,
    "resolution": 512,
    "train_batch_size": 4,
    "n_sample_imgs": 182,
    "max_train_steps": 600,
    "checkpointing_steps": 200,

    "disable_ti": false,
    "caption_model": "gpt4-v",
    "ti_lr": 0.001,
    "unet_lr": 0.0003,
    "lora_rank": 16,

    "debug": true
}
