### ISSUE TITLE
401 Client Error.

### ISSUE THREAD

**Issue by 40740** [edenartlab/sd-lora-trainer#4]
`Eden_LoRa_trainer
401 Client Error. (Request ID: Root=1-66d81c34-6ee74a8353de9ee7564a5a9f;5498fb69-a8f9-4ee0-a331-d684f635b614) Repository Not Found for url: https://huggingface.co/api/models/runwayml/stable-diffusion-v1-5/revision/main. Please make sure you specified the correct `repo_id` and `repo_type`. If you are trying to access a private or gated repo, make sure you are authenticated. Invalid username or password.`

But I trained sdxl.

**Comment by 40740** [comment]
`Loading model weights from /ComfyUI/models/checkpoints/SDXL_fixedvae_fp16.safetensors with dtype: torch.bfloat16...
Loading as SDXL model...
Loading as SD15 model...
!!! Exception during processing !!! 401 Client Error. (Request ID: Root=1-66d81c34-6ee74a8353de9ee7564a5a9f;5498fb69-a8f9-4ee0-a331-d684f635b614)

Repository Not Found for url: https://huggingface.co/api/models/runwayml/stable-diffusion-v1-5/revision/main.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "/opt/conda/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/runwayml/stable-diffusion-v1-5/revision/main

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ComfyUI/custom_nodes/sd-lora-trainer/trainer/models.py", line 17, in load_models
    pipe = StableDiffusionXLPipeline.from_single_file(
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/diffusers/loaders/single_file.py", line 409, in from_single_file
    cached_model_config_path = _download_diffusers_model_config_from_hub(
  File "/opt/conda/lib/python3.10/site-packages/diffusers/loaders/single_file.py", line 250, in _download_diffusers_model_config_from_hub
    cached_model_path = snapshot_download(
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/_snapshot_download.py", line 233, in snapshot_download
    raise api_call_error
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/_snapshot_download.py", line 164, in snapshot_download
    repo_info = api.repo_info(repo_id=repo_id, repo_type=repo_type, revision=revision, token=token)
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 2491, in repo_info
    return method(
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 2301, in model_info
    hf_raise_for_status(r)
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 352, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-66d81c34-27d036e1255a52907a4a47ea;3416a1e6-9310-4f77-8218-363c4facdd1c)`

**Comment by 40740** [comment]
Adding LR flips... (doubling the number of images from 13 to 26)
Generating 26 captions using blip in style mode...
All captions loaded from disk, skipping captioning...
WARNING: no captioning text was given and we're not doing chatgpt cleanup...
Concept mode:  style
!!! Exception during processing !!! 'tuple' object has no attribute 'format'
Traceback (most recent call last):
  File "//ComfyUI/execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "//ComfyUI/execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "//ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "//ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "//ComfyUI/custom_nodes/sd-lora-trainer/node.py", line 107, in train_lora
    progress_f = next(train_generator)
  File "//ComfyUI/custom_nodes/sd-lora-trainer/main.py", line 69, in train
    config, input_dir = preprocess(
  File "//ComfyUI/custom_nodes/sd-lora-trainer/trainer/preprocess.py", line 97, in preprocess
    config = load_and_save_masks_and_captions(
  File "//ComfyUI/custom_nodes/sd-lora-trainer/trainer/preprocess.py", line 811, in load_and_save_masks_and_captions
    captions = [config.prompt_modifier.format(caption) for caption in captions]
  File "//ComfyUI/custom_nodes/sd-lora-trainer/trainer/preprocess.py", line 811, in <listcomp>
    captions = [config.prompt_modifier.format(caption) for caption in captions]
AttributeError: 'tuple' object has no attribute 'format'
