### ISSUE TITLE
'tuple' object has no attribute 'format'

### ISSUE THREAD

**Issue by 40740** [edenartlab/sd-lora-trainer#5]
Adding LR flips... (doubling the number of images from 13 to 26)
Generating 26 captions using blip in style mode...
All captions loaded from disk, skipping captioning...
WARNING: no captioning text was given and we're not doing chatgpt cleanup...
Concept mode:  style
!!! Exception during processing !!! 'tuple' object has no attribute 'format'
Traceback (most recent call last):
  File "//ComfyUI/execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "//ComfyUI/execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "//ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "//ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "//ComfyUI/custom_nodes/sd-lora-trainer/node.py", line 107, in train_lora
    progress_f = next(train_generator)
  File "//ComfyUI/custom_nodes/sd-lora-trainer/main.py", line 69, in train
    config, input_dir = preprocess(
  File "//ComfyUI/custom_nodes/sd-lora-trainer/trainer/preprocess.py", line 97, in preprocess
    config = load_and_save_masks_and_captions(
  File "//ComfyUI/custom_nodes/sd-lora-trainer/trainer/preprocess.py", line 811, in load_and_save_masks_and_captions
    captions = [config.prompt_modifier.format(caption) for caption in captions]
  File "//ComfyUI/custom_nodes/sd-lora-trainer/trainer/preprocess.py", line 811, in <listcomp>
    captions = [config.prompt_modifier.format(caption) for caption in captions]
AttributeError: 'tuple' object has no attribute 'format'

**Comment by 40740** [comment]
comfyui

**Comment by Zorbaq** [comment]
Must be the `config.prompt_modifier` addition. No problem in 1568f10e6ec076a8810d2c6f49406401cfa01928.
